spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shvoy
    username: shvoy
    password: shvoy
  jpa:
    show-sql: true
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

aws:
  s3:
    documents-bucket: shvoy-documents-local
    endpoint-override: http://localhost:4566

logging:
  level:
    com.shvoy: DEBUG
