spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

aws:
  s3:
    documents-bucket: shvoy-documents-prod

cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID}
  app-client-id: ${COGNITO_APP_CLIENT_ID}

logging:
  level:
    com.shvoy: INFO
